Sprint 2
AdrianChojnacki/Accounting-Application pull request #1
Opened 2022-07-15 11:30 UTC by AdrianChojnacki

2022-07-24 15:02 UTC, mosilver requested changes

2022-07-24 15:02 UTC, mosilver commented on src/App.tsx
> +            <React.Suspense fallback="Loading...">
I would import it directly and not use dot notation with React

2022-07-24 15:02 UTC, mosilver commented on src/App.tsx
> +              <LazyInvoice />
I think the "Lazy" prefix in components name is unnecessary

2022-07-24 15:02 UTC, mosilver commented on src/components/Header/Header.module.css
> +.header .link {
why not to keep the simple linear convention? Then you don't must use object notation to use it

2022-07-24 15:02 UTC, mosilver commented on src/components/Header/Header.tsx
> +import HeaderCSS from "./Header.module.css";
I would import all css classes you want to use

2022-07-24 15:02 UTC, mosilver commented on src/components/Header/Header.tsx
> +            INVOICES
let's use a literal object on the top of this document to keep this static literals, it could help with translations later

2022-07-24 15:02 UTC, mosilver commented on src/components/Header/Header.tsx
> +export { Header };
why not just: export Header; ?

2022-07-24 15:02 UTC, mosilver commented on src/components/InvoicesTable/InvoicesTable.module.css
> +  font-size: 12px;
I would use rems instead px

2022-07-24 15:02 UTC, mosilver commented on src/components/InvoicesTable/InvoicesTable.types.ts
> +  render: Function;
I don't think it's a good name for function as it can be misunderstood with react native features

2022-07-24 15:02 UTC, mosilver commented on src/index.css
> +* {
anti pattern - need to be fixed

2022-07-24 15:02 UTC, mosilver commented on src/pages/Home.tsx
> +  const [posts, setPosts] = useState([]);
you don't use full typescript support here - you should type the component type (functional) and type state values (to say what values we can store in this state)

2022-07-24 20:02 UTC, mosilver commented on src/pages/Home.tsx
> +export default function Home() {
let's use the array function there

2022-07-25 16:11 UTC, AdrianChojnacki commented on src/App.tsx
> +            <React.Suspense fallback="Loading...">
Done

2022-07-25 16:12 UTC, AdrianChojnacki commented on src/App.tsx
> +              <LazyInvoice />
Done

2022-07-25 16:18 UTC, AdrianChojnacki commented on src/components/Header/Header.module.css
> +.header .link {
I don't know what You mean. Please show me some example :)

2022-07-25 16:56 UTC, AdrianChojnacki commented on src/components/Header/Header.tsx
> +import HeaderCSS from "./Header.module.css";
Can You please show me how to do it? I couldn't find it anywhere. Seems like everyone is using it the way I used it.

2022-07-25 16:58 UTC, AdrianChojnacki commented on src/components/Header/Header.tsx
> +            INVOICES
Done

2022-07-25 17:02 UTC, AdrianChojnacki commented on src/components/Header/Header.tsx
> +export { Header };
We've used that approach in our inside PGS app. Thanks to that approach I can import many components directly from components folder and all together in curly braces. I export everything from component using it's index.ts file and then export everything from components folder using main index.ts file in components folder.

2022-07-25 17:08 UTC, AdrianChojnacki commented on src/components/InvoicesTable/InvoicesTable.types.ts
> +  render: Function;
Done

2022-07-26 15:09 UTC, AdrianChojnacki commented on src/components/InvoicesTable/InvoicesTable.module.css
> +  font-size: 12px;
Done

2022-07-26 15:16 UTC, AdrianChojnacki commented on src/pages/Home.tsx
> +  const [posts, setPosts] = useState([]);
Done

2022-07-26 15:18 UTC, AdrianChojnacki commented on src/pages/Home.tsx
> +export default function Home() {
What do You mean? I don't understand :P

2022-07-26 15:39 UTC, AdrianChojnacki commented on src/index.css
> +* {
Why is it an anti pattern and how to write clean margin + padding reset?

2022-07-30 18:45 UTC, mosilver commented on src/pages/Home.tsx
> +export default function Home() {
misspell - arrow

2022-08-01 15:16 UTC, AdrianChojnacki commented on src/pages/Home.tsx
> +export default function Home() {
Done

2022-08-02 12:06 UTC, merged